cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
    
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:    
    urlpatterns += static(settings.MEDIA_URL,                          
                            document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('charge/', views.charge, name='charge'), # new
    path('', views.Payment.as_view(), name='Payment'),
    
]

shop/urls.py
from django.urls import path
from . import views
            
app_name='shop'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('shop', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
# payments/views.py
import stripe # new

from django.conf import settings

from django.views.generic.base import TemplateView
from django.shortcuts import render # new

stripe.api_key = settings.STRIPE_SECRET_KEY # new
class Payment(TemplateView):
    template_name = 'payment.html'

    
    def get_context_data(self, **kwargs): # new
        context = super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLISHABLE_KEY
        return context


def charge(request): # new
    if request.method == 'POST':
        charge = stripe.Charge.create(
            amount=500,
            currency='usd',
            description='A Django charge',
            source=request.POST['stripeToken']
        )
        return render(request, 'charge.html')

payment/templates/charge.html
{% extends "shop/base.html" %}
{% load widget_tweaks %}
{% block title %}
  The Shoppee | Successfull
{% endblock %}

{% block content %}

<div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <span class="icon-check_circle display-3 text-success"></span>
            <h2 class="display-3 text-black">Thank you!</h2>
            <p class="lead mb-5">You order was successfuly completed.</p>
            <p><a href="{% url "shop:product_list" %}" class="btn btn-sm btn-primary">Back to shop</a></p>
          </div>
        </div>
      </div>
    </div>
  
{% endblock %}

payment/templates/payment.html
{% extends "shop/base.html" %}
{% load widget_tweaks %}
{% block title %}
  Payment
{% endblock %}

{% block content %}
<div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0"><a href="/">Home</a><span class="mx-2 mb-0">/</span> <strong class="text-black">Payment</strong></div>
        </div>
      </div>
    </div>

    <div class="site-section">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-center">
              <span class="icon-check_circle display-3 text-success"></span>
              <h2 class="display-3 text-black">Make Payment</h2>
              <p><form action="{% url 'payment:charge' %}" method="post">
                  {% csrf_token %}
                  
                  <script src="https://checkout.stripe.com/checkout.js"  class="stripe-button"
                          data-key="{{ key }}"
                          data-description="The Shoppee"
                          data-amount=${{ cart.get_total_price }}
                          data-locale="auto"></script>
                </form></p>
            </div>
          </div>
        </div>
      </div>
  
{% endblock %}