cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
    
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:    
    urlpatterns += static(settings.MEDIA_URL,                          
                            document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name='orders'
urlpatterns=[
    path('create/', views.order_create, name='order_create')
]

shop/urls.py
from django.urls import path
from . import views
            
app_name='shop'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('shop', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
 
#PRODUCT_QUANTITY_CHOICES= [(i, str(i)) for i in range( 1,21)]

class CartAddProductForm(forms.Form):
    quantity=forms.IntegerField(
        #choices=PRODUCT_QUANTITY_CHOICES,
        #coerce= int
        widget=forms.NumberInput(attrs={'class': 'form-control text-center',
                                        'aria-describedby': 'button-addon1',
                                        'aria-label': 'Example text with button addon'   ,
                                        'placeholder': '',
                                        'value':'1',  
                                    }),
                                label='',                   
    )
    update=forms.BooleanField(initial=False, widget=forms.HiddenInput, required=False)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm



@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form']=CartAddProductForm(initial= {'quantity': item['quantity'], 'update':True})
    return render(request, 'cart/detail.html', {'cart': cart})


    

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}

  <div class="bg-light py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12 mb-0"><a href="/">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Cart</strong></div>
      </div>
    </div>
  </div>


  <div class="site-section">
      <div class="container">
        <div class="row mb-5">
            <div class="site-blocks-table">
              <table class="table table-bordered" >
                <thead>
                  <tr>
                    <th class="product-thumbnail">Image</th>
                    <th class="product-name">Product</th>
                    <th class="product-price">Price</th>
                    <th class="product-quantity">Quantity</th>
                    <th class="product-total">Total</th>
                    <th class="product-remove">Remove</th>
                  </tr>
                </thead>
                <tbody>
                  {% for item in cart %}
                    {% with product=item.product %}
                    <tr>
                        <td class="product-thumbnail">
                          <img src="{% if product.image %}{{ product.image.url }}
                          {% else %}{% static "img/no_image.png" %}{% endif %}" alt="Image" class="img-fluid">
                        </td>
                        <td class="product-name">
                          <h2 class="h5 text-black">{{ product.name }}</h2>
                        </td>
                        <td>${{ item.price }}</td>
                        <td>
                          <form action="{% url "cart:cart_add" product.id %}" method="post">
                            <div class="input-group mb-3" style="max-width: 120px;">
                              <div class="input-group-prepend">
                                <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
                              </div>
                              {{ item.update_quantity_form.quantity }}                            
                              <div class="input-group-append">
                                <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                              </div>
                              {{ item.update_quantity_form.update }}   
                              <input type="submit" class="btn btn-primary btn-sm btn-block" value="Update">  
                              {% csrf_token %}           
                            </div>
                          </form>    
                        </td>
                        <td>${{ item.total_price }}</td>
                        <td><a href="{% url "cart:cart_remove" product.id %}" class="btn btn-primary btn-sm">X</a></td>
                      </tr>
                    {% endwith %}
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>

          <div class="row">
          <div class="col-md-6">
            <div class="row mb-5">
              <div class="col-md-6">
                <a href="{% url "shop:product_list" %}" ><button  class="btn btn-outline-primary btn-sm btn-block">Continue Shopping</button></a>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <label class="text-black h4" for="coupon">Coupon</label>
                <p>Enter your coupon code if you have one.</p>
              </div>
              <div class="col-md-8 mb-3 mb-md-0">
                <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
              </div>
              <div class="col-md-4">
                <button class="btn btn-primary btn-sm">Apply Coupon</button>
              </div>
            </div>
          </div>
          <div class="col-md-6 pl-5">
            <div class="row justify-content-end">
              <div class="col-md-7">
                <div class="row">
                  <div class="col-md-12 text-right border-bottom mb-5">
                    <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                  </div>
                </div>
                <div class="row mb-3">
                  <div class="col-md-6">
                    <span class="text-black">Subtotal</span>
                  </div>
                  <div class="col-md-6 text-right">
                    <strong class="text-black">${{ cart.get_total_price }}</strong>
                  </div>
                </div>
                <div class="row mb-5">
                  <div class="col-md-6">
                    <span class="text-black">Total</span>
                  </div>
                  <div class="col-md-6 text-right">
                    <strong class="text-black">${{ cart.get_total_price }}</strong>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-12">
                    <a href="{% url "orders:order_create" %}" ><button class="btn btn-primary btn-lg py-3 btn-block" >Proceed To Checkout</button></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  
{% endblock %}