cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
    
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:    
    urlpatterns += static(settings.MEDIA_URL,                          
                            document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
            
app_name='shop'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('shop', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=200,
                            db_index=True)
    slug=models.SlugField(max_length=200,
                            unique=True)
    
    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
    

class Product(models.Model):
    category=models.ForeignKey(Category,
                                related_name='products',
                                on_delete=models.CASCADE)
    name=models.CharField(max_length=200, db_index=True)
    slug=models.SlugField(max_length=200, unique=True)
    image=models.ImageField(upload_to='products/%Y/%m/%d', blank='True')
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    stock=models.IntegerField(default=0)
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        index_together=(('id', 'slug'),)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])
    

  

shop/forms.py
# sendemail/forms.py
from django import forms

class ContactForm(forms.Form):
    first_name=forms.CharField( max_length=50, required=False)
    last_name=forms.CharField( max_length=50, required=False)
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

shop/views.py
# sendemail/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from .forms import ContactForm
def homepage(request):
    return render(request, 'shop/product/home.html')


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})



def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id,
                                         slug=slug,
                                         available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

def about(request): # new
        return render(request, 'shop/product/about.html')


def contact(request): # new
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            #first_name=form.cleaned_data['first_name']
            #last_name=form.cleaned_data['last_name']
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['sonishivam10@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('/')
    return render(request, "shop/product/contact.html", {'form': form})

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}The Shoppee Store{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700"> 
    <link rel="stylesheet" href="{% static "fonts/icomoon/style.css" %}">

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery-ui.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/checkout.css" %}">

    <link rel="stylesheet" href="{% static "css/aos.css" %}">

    <link rel="stylesheet" href="{% static "css/style.css" %}">
    
  </head>

  <body>
  
    <div class="site-wrap">
      <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
          <div class="container">
            <div class="row align-items-center">
  
              <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
                <form action="" class="site-block-top-search">
                  <span class="icon icon-search2"></span>
                  <input type="text" class="form-control border-0" placeholder="Search">
                </form>
              </div>
  
              <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
                <div class="site-logo">
                  <a href="/" class="js-logo-clone">Shoppers</a>
                </div>
              </div>
  
              <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                <div class="site-top-icons">
                  <ul>
                    <li><a href="#"><span class="icon icon-person"></span></a></li>
                    <li><a href="#"><span class="icon icon-heart-o"></span></a></li>
                    <li>
                        {% with total_items=cart|length %}
                        <a href="{% url "cart:cart_detail" %}" class="site-cart">
                            <span class="icon icon-shopping_cart"></span>
                            <span class="count">
                                {{ total_items}}
                        {% endwith %}
                        </span>
                      </a>
                    </li> 
                    <li class="d-inline-block d-md-none ml-md-0"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
                  </ul>
                </div> 
              </div>
  
            </div>
          </div>
        </div> 
        <nav class="site-navigation text-right text-md-center" role="navigation">
          <div class="container">
            <ul class="site-menu js-clone-nav d-none d-md-block">
              <li>
                <a href="/">Home</a>
                
              </li>
              <li>
                <a href="{% url "shop:about" %}">About</a>
              </li>
              <li><a href="{% url "shop:product_list" %}">Shop</a></li>
              <li><a href="#">Recommended</a></li>
              <li><a href="{% url "shop:contact" %}">Contact</a></li>
            </ul>
          </div>
        </nav>
      </header>


  
      
      <div >
          {% block content %}
          {% endblock %}
      </div>
    <footer class="site-footer border-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mb-5 mb-lg-0">
            <div class="row">
              <div class="col-md-12">
                <h3 class="footer-heading mb-4">Navigations</h3>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="/">Home</a></li>
                  <li><a href="{% url "cart:cart_detail" %}">Shopping cart</a></li>
                  <li><a href="#">Store builder</a></li>
                </ul>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="#">Mobile commerce</a></li>
                  <li><a href="#">Dropshipping</a></li>
                  <li><a href="#">Website development</a></li>
                </ul>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="#">Point of sale</a></li>
                  <li><a href="#">Hardware</a></li>
                  <li><a href="#">Software</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
            
          </div>
          <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
              <h3 class="footer-heading mb-4">Contact Info</h3>
              <ul class="list-unstyled">
                <li class="address">203 Fake St. Mountain View, San Francisco, California, USA</li>
                <li class="phone"><a href="tel://23923929210">+2 392 3929 210</a></li>
                <li class="email">emailaddress@domain.com</li>
              </ul>
            </div>

            <div class="block-7">
              <form action="#" method="post">
                <label for="email_subscribe" class="footer-heading">Subscribe</label>
                <div class="form-group">
                  <input type="text" class="form-control py-4" id="email_subscribe" placeholder="Email">
                  <input type="submit" class="btn btn-sm btn-primary" value="Send">
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <p>
            
            </p>
          </div>
          
        </div>
      </div>
    </footer>
  </div>

  <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
  <script src="{% static "js/jquery-ui.js" %}"></script>
  <script src="{% static "js/popper.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/owl.carousel.min.js" %}"></script>
  <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
  <script src="{% static "js/aos.js" %}"></script>
  <script src="{% static "js/checkout.js" %}"></script>
  <script src="{% static "js/main.js" %}"></script>
    
  </body>
</html>